eureka:
  client:
    serviceUrl:
      defaultZone : http://admin:admin@localhost:8080/eureka/
spring:
  application:
    name: gateway
server:
  port: 8083
zuul:
  routes:
    service0 : /service0/**
    service1 : /service1/**
  host:
    socket-timeout-millis: 1000000
    connect-timeout-millis: 2000000

ribbon:
  ReadTimeout: 100000
  ConnectionTimeout: 100000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000

